name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'   # প্রতিদিন রাত 12:00 UTC সময় চালাবে
  workflow_dispatch:      # চাইলে ম্যানুয়ালি চালাতে পারবে

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make a small change
        run: |
          echo "Daily commit at $(date -u)" >> daily.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily.txt
          git commit -m "chore: daily automated commit" || echo "no changes"
          git push
